[package]
name = "cv-hough-transform"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cv_hough_transform"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
pyo3 = "0.27.0"
